name: Build and Publish

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-build.yml
    with:
      publish: true
      image_tags: |
        ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        ghcr.io/${{ github.repository }}:latest
